# Generated by Django 4.0.4 on 2022-11-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieworld', '0003_opinion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
